spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/message
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      test-on-borrow: ${TEST_ON_BORROW:true}
      validation-query: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
logging:
  level:
    root: INFO

pool:
  core_size: 10
  max_size: 10
  keepalive_second: 60
  queue_capacity: 1000
